M48
; DRILL file {KiCad (7.0.0)} date Thu Apr 13 18:09:35 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-13T18:09:35+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X4.2835Y-3.9555
X4.2835Y-4.1831
T2
X4.437Y-3.2776
X4.5Y-4.8012
X6.9055Y-3.2657
X6.9193Y-4.8228
T0
M30
